- coop:
    available: true
    max: -1
    min: 2
  download_size: 0.6
  genres:
  - Adventure
  - Arcade
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co49x5.jpg
  installed_size: 1.0
  multiplayer:
    available: true
    max: -1
    min: 1
  name: Minecraft
  self_hosted: true
  slug: minecraft
  summary: Minecraft focuses on allowing the player to explore, interact with, and
    modify a dynamically-generated map made of one-cubic-meter-sized blocks. In addition
    to blocks, the environment features plants, mobs, and items. Some activities in
    the game include mining for ore, fighting hostile mobs, and crafting new blocks
    and tools by gathering various resources found in the game. The game's open-ended
    model allows players to create structures, creations, and artwork on various multiplayer
    servers or their single-player maps. Other features include redstone circuits
    for logic computations and remote actions, minecarts and tracks, and a mysterious
    underworld called the Nether. A designated but completely optional goal of the
    game is to travel to a dimension called the End, and defeat the ender dragon.
- coop:
    available: true
    max: 4
    min: 2
  download_size: 30.0
  genres:
  - Shooter
  - Role-playing (RPG)
  - Adventure
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co3wml.jpg
  installed_size: 40.0
  multiplayer:
    available: true
    max: 4
    min: 2
  name: Dying Light
  self_hosted: false
  slug: dying-light
  summary: "Dying Light is a first-person, action survival horror game set in a vast\
    \ and dangerous open world. During the day, players traverse an expansive urban\
    \ environment overrun by a vicious outbreak, scavenging the world for supplies\
    \ and crafting weapons to defend against the growing infected population. At night,\
    \ the hunter becomes the hunted, as the infected become aggressive and more dangerous.\
    \ Most frightening are the predators which only appear after sundown. Players\
    \ must use everything in their power to survive until the morning\u2019s first\
    \ light."
- coop:
    available: true
    max: 2
    min: 2
  download_size: 8.0
  genres:
  - Shooter
  - Adventure
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co1nrn.jpg
  installed_size: 10.0
  multiplayer:
    available: false
    max: 0
    min: 0
  name: Saints Row IV
  self_hosted: false
  slug: saints-row-iv
  summary: Unlike the first three games in the franchise, Saints Row 4 does not center
    around the main character defeating three rival gangs in order to take over a
    city. The Saints have now become a household name, and their leader has become
    the president of the Unites States. The antagonists in Saints Row 4 are an invading
    alien race known as the Zin. Most of the game takes place within a computer simulation
    of the city of Steelport controlled by the Zin, where the protagonist is attempting
    to free himself and his companions.
- coop:
    available: true
    max: 2
    min: 2
  download_size: 6.0
  genres:
  - Shooter
  - Racing
  - Adventure
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co2634.jpg
  installed_size: 8.0
  multiplayer:
    available: false
    max: 0
    min: 0
  name: 'Saints Row: The Third'
  self_hosted: false
  slug: saints-row-the-third
  summary: 'Saints Row: The Third is the first Saints Row game that takes place in
    the city of Steelport. Much like the first two games, the story revolves around
    the Saints destroying and absorbing three rival gangs, taking over the city in
    the process. In Saints Row: The Third, these three gangs are the Morningstar,
    the Luchadores, and the Deckers. Unlike the first two games, these three gangs
    are all controlled by a criminal organization known as The Syndicate, which the
    saints must also deal with.'
- coop:
    available: true
    max: 16
    min: 2
  download_size: 0.2
  genres:
  - Platform
  - Role-playing (RPG)
  - Strategy
  - Adventure
  - Indie
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co1rbo.jpg
  installed_size: 0.2
  multiplayer:
    available: true
    max: 16
    min: 1
  name: Terraria
  self_hosted: true
  slug: terraria
  summary: 'Dig, Fight, Explore, Build: The very world is at your fingertips as you
    fight for survival, fortune, and glory. Will you delve deep into cavernous expanses
    in search of treasure and raw materials with which to craft ever-evolving gear,
    machinery, and aesthetics? Perhaps you will choose instead to seek out ever-greater
    foes to test your mettle in combat? Maybe you will decide to construct your own
    city to house the host of mysterious allies you may encounter along your travels?
    In the World of Terraria, the choice is yours!'
- coop:
    available: true
    max: -1
    min: 2
  download_size: 0.8
  genres:
  - Platform
  - Role-playing (RPG)
  - Adventure
  - Indie
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co4b19.jpg
  installed_size: 1.0
  multiplayer:
    available: true
    max: -1
    min: 1
  name: Starbound
  self_hosted: true
  slug: starbound
  summary: "You\u2019ve fled your home, only to find yourself lost in space with a\
    \ damaged ship. Your only option is to beam down to the planet below and gather\
    \ the resources you need to repair your ship and set off to explore the vast,\
    \ infinite universe\u2026\n\nIn Starbound, you create your own story - there\u2019\
    s no wrong way to play! You may choose to save the universe from the forces that\
    \ destroyed your home, uncovering greater galactic mysteries in the process, or\
    \ you may wish to forego a heroic journey entirely in favor of colonizing uncharted\
    \ planets."
- coop:
    available: true
    max: -1
    min: 2
  download_size: 0.8
  genres:
  - Simulator
  - Strategy
  - Indie
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co1tfy.jpg
  installed_size: 1.2
  multiplayer:
    available: true
    max: -1
    min: 1
  name: Factorio
  self_hosted: true
  slug: factorio
  summary: You will be mining resources, researching technologies, building infrastructure,
    automating production and fighting enemies. Use your imagination to design your
    factory, combine simple elements into ingenious structures, apply management skills
    to keep it working and finally protect it from the creatures who don't really
    like you.
- coop:
    available: true
    max: 4
    min: 2
  download_size: 10.0
  genres:
  - Simulator
  - Strategy
  - Adventure
  - Indie
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co1i2d.jpg
  installed_size: 15.0
  multiplayer:
    available: false
    max: 0
    min: 0
  name: Satisfactory
  self_hosted: true
  slug: satisfactory
  summary: "Satisfactory is an FPS open-world factory building sim. You play as an\
    \ engineer on an alien planet tasked to complete \u2018Project Assembly\u2019\
    \ - a massive machine for a mysterious purpose. Conquer nature, build multi-story\
    \ factories, and automate to satisfaction!"
- coop:
    available: true
    max: 4
    min: 2
  download_size: 0.2
  genres:
  - Real Time Strategy (RTS)
  - Strategy
  - Indie
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co2303.jpg
  installed_size: 0.1
  multiplayer:
    available: true
    max: 4
    min: 2
  name: Business Tour
  self_hosted: false
  slug: business-tour
  summary: Business Tour is an online board game based on the most popular tabletop
    game in the world.
- coop:
    available: true
    max: 4
    min: 2
  download_size: 30.0
  genres:
  - Shooter
  - Adventure
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co1kwl.jpg
  installed_size: 40.0
  multiplayer:
    available: true
    max: 4
    min: 2
  name: 'Dying Light: The Following'
  self_hosted: false
  slug: dying-light-the-following
  summary: "Dying Light: The Following is a massive expansion to Dying Light and the\
    \ untold chapter of Kyle Crane\u2019s story. Take to a vast new area that will\
    \ transform your Dying Light experience through new game mechanics, environments\
    \ and challenges on top of the established core of what made Dying Light a break\
    \ away success for millions of players around the globe."
- coop:
    available: true
    max: 4
    min: 2
  download_size: 50.0
  genres:
  - Role-playing (RPG)
  - Adventure
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co31k4.jpg
  installed_size: 60.0
  multiplayer:
    available: false
    max: 0
    min: 0
  name: 'Dying Light 2: Stay Human'
  self_hosted: false
  slug: dying-light-2-stay-human
  summary: The last great human settlement exists within an unforgiving, infected
    world. Exceptional agility and combat skills make you a powerful ally and a valuable
    commodity. With your unique abilities you have the power to be an agent of change
    within this decaying metropolis. Use it wisely.
- coop:
    available: true
    max: 2
    min: 2
  download_size: 30.0
  genres:
  - Shooter
  - Adventure
  icon: //images.igdb.com/igdb/image/upload/t_thumb/co21a6.jpg
  installed_size: 40.0
  multiplayer:
    available: true
    max: 12
    min: 1
  name: Far Cry 5
  self_hosted: false
  slug: far-cry-5
  summary: "Welcome to Hope County, Montana, land of the free and the brave, but also\
    \ home to a fanatical doomsday cult known as The Project at Eden\u2019s Gate that\
    \ is threatening the community's freedom. Stand up to the cult\u2019s leader,\
    \ Joseph Seed and the Heralds, and spark the fires of resistance that will liberate\
    \ the besieged community.\n\nIn this expansive world, your limits and creativity\
    \ will be tested against the biggest and most ruthless baddest enemy Far Cry has\
    \ ever seen. It\u2019ll be wild and it\u2019ll get weird, but as long as you keep\
    \ your wits about you, the residents of Hope County can rest assured knowing you\u2019\
    re their beacon of hope."
